name: Build & deploy guide

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - uses: actions/cache@v31
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/book.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: setup env to build website
        run: |
          npm install gitbook-cli -g
          gitbook install
      - name: build website
        run: |
          gitbook build . ./build
          rm -rf ./build/.github
          echo "" > ./build/.nojekyll
    
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
          with:
            # Artifact name
            name: mavlink_guide
            # A file, directory or wildcard pattern that describes what to upload
            path: ./build
            # The desired behavior if no files are found using the provided path.
            if-no-files-found: error
            
        # Then we'll work out how to deploy
        
